#!/bin/bash
#
# Perform necessary berta removal steps
# after package is uninstalled.
#

PROGNAME=$(basename $0)
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/berta
CONFIG_DIR=/etc/berta
BIN_DIR=/usr/bin
CRON_DIR=/etc/cron.d
INIT_DIR=/etc/init.d

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if [ "X$1" = "Xupgrade" ] || [ "X$1" = "X1" ]; then
  echo "Skipping clean-up, this is an upgrade!"
  exit 0
fi

# clean up cron integration
if [ -f "$CRON_DIR/berta" ]; then
  rm $CRON_DIR/berta
fi

# clean up init scripts
if [ -f "$INIT_DIR/berta-cron" ]; then
  rm $INIT_DIR/berta-cron
fi

# clean up links
if [ -L "$BIN_DIR/berta" ]; then
  rm $BIN_DIR/berta
fi

echo "berta has been uninstalled!"

exit 0
